## Docker Compose configuration for dev iteration
##
## Data is transient by using named vols.
## Run: docker-compose -f ./docker-compose.dev.yml up
services:

  server:
    build:
      context: ./server
      target: development
    depends_on:
      - sql
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CONFIG_PATH: /opt/app/config.yaml
      THREADS: 4
    volumes:
      - ./data:/data
      - ./server/:/opt/app/

  client:
    build:
      context: ./client
      target: development
    depends_on:
      - server
    volumes:
      - "data:/data:ro"
      - "./client/:/opt/app/"
      - "/opt/app/public/"
    ports:
      - "${PORT}:80"
      - "8080:8080"

  sql:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - sql:/var/lib/postgresql/data

volumes:
  data:
  sql:
