services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: my-szuru-server
    depends_on:
      - sql
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CONFIG_PATH: /opt/app/config.yaml
      THREADS: 4
    ports:
      - "6666:6666"
    volumes:
      - ./data:/data
      - ./server/config.yaml:/opt/app/config.yaml
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: my-szuru-client
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
      BASE_URL: /
    ports:
      - "8090:80"
    volumes:
      - ./data:/data:ro
    restart: unless-stopped

  sql:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped

